name: .NET Core

on:
  release:
    types: [created]
    name: Release  

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Build
        shell: bash
        run: |
          release_name=Group-Calling
          unset CI
          # Build everything
          dotnet publish ./Calling -c Release -o "$release_name"

          7z a -tzip "group-calling.zip" "./${release_name}/*"

          # Delete output directory
          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "group-calling.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
